language: csharp  
mono: none
dotnet: 3.1
before_script:
  - dotnet restore
  - dotnet build --configuration Release
script:  
  - dotnet test --configuration Release --collect:"XPlat Code Coverage" --no-build /p:CoverletOutputFormat=opencover
after_script:
  - bash <(curl -s https://codecov.io/bash)
